version: "2"
services:
  hedwig:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: sezzh/hedwig
    depends_on:
      - db
    ports:
      - "5000:5000"
      - "5678:5678"
    environment:
      - PYTHONPATH=/home/app/hedwig/lib
      - HEDWIG_DIR=/home/app/hedwig
      - TZ=America/Mexico_City
    volumes:
      - .:/home/app/hedwig
  db:
    image: mariadb:10.1.16
    volumes_from:
      - data
    depends_on:
      - data
    environment:
      - MYSQL_ROOT_PASSWORD=rjbits
      - MYSQL_DATABASE=hedwig
    ports:
      - "3306:3306"
  data:
    image: busybox
    volumes:
      - data_db_hedwig:/var/lib/mysql
  apache:
    image: httpd:2.4.23
volumes:
  data_db_hedwig:
    external: true
